config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :athletes
  resources :sports
  resources :schedule
  get 'welcome/athletes'

  get 'welcome/schedule'
#  get '/schedules(.:format)' => 'schedules#show'

  get 'welcome/sports'

  get 'welcome/Index'
  root 'welcome#Index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
class Athlete < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/sport.rb
class Sport < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :set_athlete, only: [:show, :edit, :update, :destroy]

  # GET /athletes
  # GET /athletes.json
  def index
    @athletes = Athlete.all
  end

  # GET /athletes/1
  # GET /athletes/1.json
  def show
  end

  # GET /athletes/new
  def new
    @athlete = Athlete.new
  end

  # GET /athletes/1/edit
  def edit
  end

  # POST /athletes
  # POST /athletes.json
  def create
    @athlete = Athlete.new(athlete_params)

    respond_to do |format|
      if @athlete.save
        format.html { redirect_to @athlete, notice: 'Athlete was successfully created.' }
        format.json { render :show, status: :created, location: @athlete }
      else
        format.html { render :new }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /athletes/1
  # PATCH/PUT /athletes/1.json
  def update
    respond_to do |format|
      if @athlete.update(athlete_params)
        format.html { redirect_to @athlete, notice: 'Athlete was successfully updated.' }
        format.json { render :show, status: :ok, location: @athlete }
      else
        format.html { render :edit }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes/1
  # DELETE /athletes/1.json
  def destroy
    @athlete.destroy
    respond_to do |format|
      format.html { redirect_to athletes_url, notice: 'Athlete was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athlete
      @athlete = Athlete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def athlete_params
      params.require(:athlete).permit(:athlete_name, :gender, :class_year, :sports_id, :team_id, :position)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:schedule_date, :location_id, :schedule_type, :score, :team_id)
    end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]

  # GET /sports
  # GET /sports.json
  def index
    @sports = Sport.all
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
  end

  # GET /sports/new
  def new
    @sport = Sport.new
  end

  # GET /sports/1/edit
  def edit
  end

  # POST /sports
  # POST /sports.json
  def create
    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1
  # PATCH/PUT /sports/1.json
  def update
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    @sport.destroy
    respond_to do |format|
      format.html { redirect_to sports_url, notice: 'Sport was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sport_params
      params.require(:sport).permit(:sports_id, :sports_type)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def Index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/helpers/db_schedules_helper.rb
module DbSchedulesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/athletes/_form.html.erb
<%= form_with(model: athlete, local: true) do |form| %>
  <% if athlete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(athlete.errors.count, "error") %> prohibited this athlete from being saved:</h2>

      <ul>
      <% athlete.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :athlete_name %>
    <%= form.text_area :athlete_name, id: :athlete_athlete_name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_area :gender, id: :athlete_gender %>
  </div>

  <div class="field">
    <%= form.label :class_year %>
    <%= form.number_field :class_year, id: :athlete_class_year %>
  </div>

  <div class="field">
    <%= form.label :sports_id %>
    <%= form.number_field :sports_id, id: :athlete_sports_id %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.number_field :team_id, id: :athlete_team_id %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_area :position, id: :athlete_position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/athletes/edit.html.erb
<h1>Editing Athlete</h1>

<%= render 'form', athlete: @athlete %>

<%= link_to 'Show', @athlete %> |
<%= link_to 'Back', athletes_path %>

app/views/athletes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Athletes</h1>

<table>
  <thead>
    <tr>
      <th>Athlete name</th>
      <th>Gender</th>
      <th>Class year</th>
      <th>Sports</th>
      <th>Team</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @athletes.each do |athlete| %>
      <tr>
        <td><%= athlete.athlete_name %></td>
        <td><%= athlete.gender %></td>
        <td><%= athlete.class_year %></td>
        <td><%= athlete.sports_id %></td>
        <td><%= athlete.team_id %></td>
        <td><%= athlete.position %></td>
        <td><%= link_to 'Show', athlete %></td>
        <td><%= link_to 'Edit', edit_athlete_path(athlete) %></td>
        <td><%= link_to 'Destroy', athlete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Athlete', new_athlete_path %>

app/views/athletes/new.html.erb
<h1>New Athlete</h1>

<%= render 'form', athlete: @athlete %>

<%= link_to 'Back', athletes_path %>

app/views/athletes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Athlete name:</strong>
  <%= @athlete.athlete_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @athlete.gender %>
</p>

<p>
  <strong>Class year:</strong>
  <%= @athlete.class_year %>
</p>

<p>
  <strong>Sports:</strong>
  <%= @athlete.sports_id %>
</p>

<p>
  <strong>Team:</strong>
  <%= @athlete.team_id %>
</p>

<p>
  <strong>Position:</strong>
  <%= @athlete.position %>
</p>

<%= link_to 'Edit', edit_athlete_path(@athlete) %> |
<%= link_to 'Back', athletes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sportsapp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :schedule_date %>
    <%= form.datetime_select :schedule_date, id: :schedule_schedule_date %>
  </div>

  <div class="field">
    <%= form.label :location_id %>
    <%= form.number_field :location_id, id: :schedule_location_id %>
  </div>

  <div class="field">
    <%= form.label :schedule_type %>
    <%= form.text_field :schedule_type, id: :schedule_schedule_type %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score, id: :schedule_score %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.number_field :team_id, id: :schedule_team_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Schedule date</th>
      <th>Location</th>
      <th>Schedule type</th>
      <th>Score</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.schedule_date %></td>
        <td><%= schedule.location_id %></td>
        <td><%= schedule.schedule_type %></td>
        <td><%= schedule.score %></td>
        <td><%= schedule.team_id %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Schedule date:</strong>
  <%= @schedule.schedule_date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @schedule.location_id %>
</p>

<p>
  <strong>Schedule type:</strong>
  <%= @schedule.schedule_type %>
</p>

<p>
  <strong>Score:</strong>
  <%= @schedule.score %>
</p>

<p>
  <strong>Team:</strong>
  <%= @schedule.team_id %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>

app/views/sports/_form.html.erb
<%= form_with(model: sport, local: true) do |form| %>
  <% if sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% sport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sports_id %>
    <%= form.number_field :sports_id, id: :sport_sports_id %>
  </div>

  <div class="field">
    <%= form.label :sports_type %>
    <%= form.text_area :sports_type, id: :sport_sports_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing Sport</h1>

<%= render 'form', sport: @sport %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sports</h1>

<table>
  <thead>
    <tr>
      <th>Sports</th>
      <th>Sports type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sports.each do |sport| %>
      <tr>
        <td><%= sport.sports_id %></td>
        <td><%= sport.sports_type %></td>
        <td><%= link_to 'Show', sport %></td>
        <td><%= link_to 'Edit', edit_sport_path(sport) %></td>
        <td><%= link_to 'Destroy', sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sport', new_sport_path %>

app/views/sports/new.html.erb
<h1>New Sport</h1>

<%= render 'form', sport: @sport %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sports:</strong>
  <%= @sport.sports_id %>
</p>

<p>
  <strong>Sports type:</strong>
  <%= @sport.sports_type %>
</p>

<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>

app/views/welcome/Index.html.erb
<h1>Welcome to the Intramural Sports Website</h1>
<p>Please select an option below</p>

<%= link_to "Look up schedule", schedules_path %>
<%= link_to "Look up athletes", athletes_path %>
<%= link_to "Look up sports", sports_path %>

app/views/welcome/athletes.html.erb
<h1>Welcome Athletes</h1>
<p>Here are the athletes currently playing intramural sports</p>
<%= link_to "Look up athletes", athletes_path %>

app/views/welcome/schedule.html.erb
<h1>Full Schedule</h1>
<p>Below is the schedule of games and practices</p>

app/views/welcome/sports.html.erb
<h1>Sports</h1>
<p>Here are the sports available to play</p>